version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "codereach"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ot9gn38m70u9"
s3_prefix = "codereach"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
